INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (1, 'tony', 'Anything St.', 'Toronto', 'ON', 'MT36P0', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (1, 'tony', 'This St.', 'Toronto', 'ON', 'RY36P0', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (1, 'tony', 'That St.', 'Toronto', 'ON', 'MT72P0', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (3, 'sabrina', 'The Other St.', 'Toronto', 'ON', 'MX09P0', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (4, 'mac', 'Not this but that St.', 'Ottawa', 'ON', 'MT3L8D', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (9, 'bk', 'Capital St.', 'Ottawa', 'ON', 'MT3L8D', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (8, 'wendys', 'Rideu Canal St.', 'Ottawa', 'ON', 'P03L8D', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (7, 'harveys', 'Parliament St.', 'Ottawa', 'ON', 'ST7S8D', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (3, 'abc', 'Snow St.', 'Ottawa', 'ON', 'T54L8D', 'Canada', true);
INSERT INTO restaurants (owner_id, name, street, city, province, postal_code, country, active) VALUES (4, 'cda','No way St.', 'Hamilton', 'ON', 'K3EL8D', 'Canada', true);
