INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (1, 1, 4, 'good food');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (4, 2, 1, 'horrible stay away!');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (5, 4, 5, 'Amazing FOOD!');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (4, 1, 4, 'Good customer services.');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (9, 5, 5, 'Warm and excellent service');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (4, 5, 1, 'bad food');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (1, 7, 2, 'stay away!');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (2, 8, 5, 'amazing!');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (3, 10, 4, '5/5');
INSERT INTO restaurant_reviews (user_id, restaurant_id, rating, review) VALUES (10, 3, 5, 'restaurant was perfect.');
