DROP TABLE IF EXISTS food_items CASCADE;

CREATE TABLE food_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  ingredient VARCHAR(255) NOT NULL,
  price DECIMAL NOT NULL
);
